// GENERATED by `npm run api:types` from specs/001-shop-browse-cart-checkout/contracts/openapi.yaml.
// Do not edit by hand.

export interface paths {
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List of categories for navigation (FR-002) */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product list with filters, sorting and pagination (FR-001–FR-004)
         * @description Parameters map 1:1 to the URL parameters of the list page in the frontend
         *     (see `frontend-routes.md`). Returns active products only.
         */
        get: operations["searchProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product page (FR-005) */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The guest's priced cart (FR-010, FR-011, FR-013)
         * @description An empty cart when the guest has none yet. May set the `shop_guest` cookie.
         */
        get: operations["getCart"];
        put?: never;
        post?: never;
        /** Clear the whole cart (FR-009) */
        delete: operations["clearCart"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a product (quantities are merged, FR-006–FR-008) */
        post: operations["addToCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/lines/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Set the line quantity; 0 removes the line (FR-008, FR-009)
         * @description A quantity larger than available is capped at `min(stock, 99)`; the response then
         *     contains the `QUANTITY_CAPPED` message in `messages` (US3-3).
         */
        put: operations["changeQuantity"];
        post?: never;
        /** Remove a line (idempotent) */
        delete: operations["removeLine"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/accept-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge price changes (FR-011, R-09) */
        post: operations["acceptPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an order and start the Stripe Checkout payment (FR-014–FR-018)
         * @description The backend re-prices the cart and compares it with `confirmedSummary` (R-14).
         *     If they match, it creates an `AWAITING_PAYMENT` order with immutable lines,
         *     creates a Stripe session and returns `paymentUrl`, to which the frontend
         *     redirects. The cart is NOT cleared in this step.
         */
        post: operations["placeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Confirmation page — only for the guest who placed the order (FR-023)
         * @description Returns `404` when the order does not exist OR belongs to another guest (R-15).
         *     The frontend polls every 2 s while status = `AWAITING_PAYMENT` (max. 60 s, US4-6).
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook (FR-019, FR-020) — called by Stripe only
         * @description Details of handled events: `stripe-webhook.md`. The body is processed as
         *     raw text (required for signature verification). No cookie required.
         */
        post: operations["stripeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AvailabilityStatus: "AVAILABLE" | "LOW_STOCK" | "UNAVAILABLE";
        Category: {
            slug: string;
            name: string;
        };
        Image: {
            /** @example /images/headphones-1.jpg */
            url: string;
            alt: string;
        };
        ProductSummary: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            priceMinor: number;
            status: components["schemas"]["AvailabilityStatus"];
            image: components["schemas"]["Image"];
            /** @description `min(stock, 99)`; 0 for unavailable products — button disabled (US2-4) */
            maxAddable: number;
        };
        ProductSearchResult: {
            products: components["schemas"]["ProductSummary"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
            totalPages: number;
        };
        ProductDetails: {
            /** Format: int64 */
            id: number;
            name: string;
            description: string;
            /** Format: int64 */
            priceMinor: number;
            status: components["schemas"]["AvailabilityStatus"];
            images: components["schemas"]["Image"][];
            category: components["schemas"]["Category"];
            maxAddable: number;
        };
        AddLineRequest: {
            /** Format: int64 */
            productId: number;
            quantity: number;
        };
        ChangeQuantityRequest: {
            quantity: number;
        };
        CartLine: {
            /** Format: int64 */
            productId: number;
            name: string;
            imageUrl: string;
            /**
             * Format: int64
             * @description Current catalog price
             */
            unitPriceMinor: number;
            quantity: number;
            /** Format: int64 */
            lineTotalMinor: number;
            status: components["schemas"]["AvailabilityStatus"];
            maxQuantity: number;
            priceChanged: boolean;
            /**
             * Format: int64
             * @description Price at the time of adding, when `priceChanged = true`
             */
            previousPriceMinor?: number | null;
            quantityExceedsStock: boolean;
        };
        Message: {
            /** @enum {string} */
            code: "QUANTITY_CAPPED" | "PRICE_CHANGED" | "PRODUCT_UNAVAILABLE" | "QUANTITY_EXCEEDS_STOCK";
            /** Format: int64 */
            productId?: number | null;
            /** @description Customer-facing message to display (Polish UI copy) */
            text: string;
        };
        Cart: {
            lines: components["schemas"]["CartLine"][];
            /** @description Header counter (FR-013) */
            itemCount: number;
            /** Format: int64 */
            totalMinor: number;
            canPlaceOrder: boolean;
            messages: components["schemas"]["Message"][];
        };
        ConfirmedLine: {
            /** Format: int64 */
            productId: number;
            quantity: number;
            /** Format: int64 */
            unitPriceMinor: number;
        };
        PlaceOrderRequest: {
            /** Format: email */
            email: string;
            fullName: string;
            streetAndNumber: string;
            postalCode: string;
            city: string;
            /** @description The summary seen by the customer — for comparison only (R-14) */
            confirmedSummary: {
                lines: components["schemas"]["ConfirmedLine"][];
                /** Format: int64 */
                totalMinor: number;
            };
        };
        StartedPayment: {
            /** @example ORD-7K2Q9M4XTB */
            number: string;
            /**
             * Format: uri
             * @description URL of the hosted Stripe Checkout page
             */
            paymentUrl: string;
        };
        /** @enum {string} */
        OrderStatus: "AWAITING_PAYMENT" | "PAID" | "PAYMENT_FAILED" | "NEEDS_REVIEW";
        OrderLine: {
            name: string;
            /** Format: int64 */
            unitPriceMinor: number;
            quantity: number;
            /** Format: int64 */
            lineTotalMinor: number;
        };
        Order: {
            number: string;
            status: components["schemas"]["OrderStatus"];
            lines: components["schemas"]["OrderLine"][];
            /** Format: int64 */
            totalMinor: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            paidAt?: string | null;
        };
        FieldError: {
            /** @example postalCode */
            field: string;
            /**
             * @description Customer-facing message (Polish UI copy)
             * @example Kod pocztowy musi mieć format NN-NNN
             */
            message: string;
        };
        /** @description RFC 9457 Problem Details */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            /** @description Customer-facing message (Polish UI copy), no sensitive data */
            detail?: string;
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "NOT_FOUND" | "QUANTITY_EXCEEDS_LIMIT" | "PRODUCT_UNAVAILABLE" | "SUMMARY_OUTDATED" | "CART_NOT_ORDERABLE" | "ORDER_ALREADY_PAID" | "PAYMENT_UNAVAILABLE" | "CONCURRENCY_CONFLICT" | "INTERNAL_ERROR";
            maxQuantity?: number | null;
            errors?: components["schemas"]["FieldError"][];
        };
        ProblemWithCart: components["schemas"]["Problem"] & {
            cart?: components["schemas"]["Cart"];
        };
    };
    responses: {
        /** @description Invalid input (`code = VALIDATION_ERROR`, errors per field) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist or is not available to this guest */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ProductId: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Request correlation identifier (R-32). Echo of the request value if it matches the
         *     pattern, otherwise a UUID generated by the backend. Present in every response.
         */
        "X-Request-Id": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories in display order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    searchProducts: {
        parameters: {
            query?: {
                /** @description Category slug */
                category?: string;
                /**
                 * @description Name fragment; ignores letter case and Polish diacritics (FR-003).
                 *     Trimmed to 100 characters; special characters allowed.
                 */
                q?: string;
                /** @description Minimum price in grosze */
                minPrice?: number;
                /** @description Maximum price in grosze */
                maxPrice?: number;
                sort?: "name_asc" | "price_asc" | "price_desc";
                /** @description Page number, starting from 0 */
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of results (empty list = "no results") */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSearchResult"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetails"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart priced with current catalog prices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    clearCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empty cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    addToCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddLineRequest"];
            };
        };
        responses: {
            /** @description Cart after the addition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            /**
             * @description `QUANTITY_EXCEEDS_LIMIT` (field `maxQuantity` = how many can still be added in total
             *     to the line) or `PRODUCT_UNAVAILABLE`. Cart unchanged.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    changeQuantity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeQuantityRequest"];
            };
        };
        responses: {
            /** @description Cart after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    removeLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart after the removal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    acceptPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart without `priceChanged` flags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    placeOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceOrderRequest"];
            };
        };
        responses: {
            /** @description Order created, payment started */
            201: {
                headers: {
                    /** @description /api/orders/{number} */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartedPayment"];
                };
            };
            400: components["responses"]["ValidationError"];
            /**
             * @description `SUMMARY_OUTDATED` — price/availability/contents changed; `cart` contains the
             *     current summary for re-confirmation (US4-7).
             *     `CART_NOT_ORDERABLE` — the cart is empty or has unavailable lines (FR-014).
             *     `ORDER_ALREADY_PAID` — the guest's previous session has already been paid (R-13).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemWithCart"];
                };
            };
            /** @description `PAYMENT_UNAVAILABLE` — the provider is temporarily unavailable; cart unchanged. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    stripeWebhook: {
        parameters: {
            query?: never;
            header: {
                "Stripe-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Event processed, ignored or duplicate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid signature / unreadable body — no effects */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Technical error — Stripe will retry delivery */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
