// Generates src/api/schema.d.ts from the OpenAPI contract (API-first, research R-19).
//   npm run api:types              -> (re)generate the file
//   npm run api:types -- --check   -> fail when the file differs from the contract (CI)
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const contract = path.resolve(root, '../specs/001-shop-browse-cart-checkout/contracts/openapi.yaml');
const target = path.resolve(root, 'src/api/schema.d.ts');
const header =
  '// GENERATED by `npm run api:types` from specs/001-shop-browse-cart-checkout/contracts/openapi.yaml.\n' +
  '// Do not edit by hand.\n\n';

const ast = await openapiTS(new URL(`file://${contract.replace(/\\/g, '/')}`));
const generated = header + astToString(ast);

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = await readFile(target, 'utf8');
  } catch {
    // missing file = outdated
  }
  if (current.replace(/\r\n/g, '\n') !== generated.replace(/\r\n/g, '\n')) {
    console.error('src/api/schema.d.ts is out of date with the OpenAPI contract. Run `npm run api:types`.');
    process.exit(1);
  }
  console.log('src/api/schema.d.ts is up to date.');
} else {
  await writeFile(target, generated, 'utf8');
  console.log(`Generated ${path.relative(root, target)}`);
}
