package com.project.custom;

import com.project.custom.support.IntegrationTest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ClassPathResource;
import org.springframework.test.web.servlet.MockMvc;
import org.yaml.snakeyaml.Yaml;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

import java.io.IOException;
import java.io.InputStream;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * The implemented API against the contract: the paths, methods and response codes generated by springdoc
 * ({@code /v3/api-docs}) must match {@code openapi/shop-api.yaml} (constitution, contract-first).
 */
class OpenApiContractTest extends IntegrationTest {

    private static final Set<String> HTTP_METHODS = Set.of("get", "post", "put", "patch", "delete");

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JsonMapper jsonMapper;

    @Test
    void implementedPathsAndMethodsMatchTheContract() throws Exception {
        assertThat(operations(generated())).isEqualTo(operations(contract()));
    }

    @Test
    void everyResponseCodeOfTheImplementationIsDeclaredInTheContract() throws Exception {
        JsonNode generated = generated();
        JsonNode contract = contract();

        for (String operation : operations(generated)) {
            String[] parts = operation.split(" ", 2);
            Set<String> declared = responseCodes(contract, parts[1], parts[0]);
            Set<String> implemented = responseCodes(generated, parts[1], parts[0]);
            assertThat(declared).as("response codes of " + operation).containsAll(implemented);
        }
    }

    @Test
    void everySuccessResponseOfTheContractIsImplemented() throws Exception {
        JsonNode generated = generated();
        JsonNode contract = contract();

        for (String operation : operations(contract)) {
            String[] parts = operation.split(" ", 2);
            Set<String> successCodes = new TreeSet<>(responseCodes(contract, parts[1], parts[0]));
            successCodes.removeIf(code -> !code.startsWith("2"));
            assertThat(responseCodes(generated, parts[1], parts[0]))
                    .as("2xx response codes of " + operation).containsAll(successCodes);
        }
    }

    private JsonNode generated() throws Exception {
        String body = mockMvc.perform(get("/v3/api-docs"))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();
        return jsonMapper.readTree(body);
    }

    private JsonNode contract() throws IOException {
        try (InputStream in = new ClassPathResource("openapi/shop-api.yaml").getInputStream()) {
            Object document = new Yaml().load(in);
            return jsonMapper.valueToTree(document instanceof Map<?, ?> map ? map : Map.of());
        }
    }

    /** {@code "GET /api/products/{id}"} for every operation of the document. */
    private static Set<String> operations(JsonNode document) {
        Set<String> operations = new TreeSet<>();
        document.path("paths").properties().forEach(path -> path.getValue().propertyNames().stream()
                .filter(HTTP_METHODS::contains)
                .forEach(method -> operations.add(method.toUpperCase() + " " + path.getKey())));
        return operations;
    }

    private static Set<String> responseCodes(JsonNode document, String path, String method) {
        Set<String> codes = new TreeSet<>();
        document.path("paths").path(path).path(method.toLowerCase()).path("responses").propertyNames()
                .forEach(codes::add);
        return codes;
    }
}
